# Generated by Django 5.1.4 on 2024-12-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_deposit_delete_transaction'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbankaccount',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
        migrations.DeleteModel(
            name='UserBankAccount',
        ),
    ]
