# Generated by Django 5.1.4 on 2024-12-20 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_purchase_delete_borrowhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
